---
- name: ping windows Servers 
  ansible.windows.win_ping:

- name: Install java  on windows server
  chocolatey.chocolatey.win_chocolatey:
    name: temurin17
    state: present


- name: install postgresql on windows server
  chocolatey.chocolatey.win_chocolatey:
    name: postgresql
    state: present

- name: get the postgresql version details
  ansible.windows.win_shell: (Get-Service postgresql-x64-*).name
  register: postgresql_name
  changed_when: false

- name: Display Postgresql version
  ansible.windows.debug:
  var:
    postgresql_name.stdout


- name: start postgresql server on windows server
  ansible.windows.win_service:
    name: "{{ postgresql_name.stdout | trim }}"
    state: started

