---
- name: ping windows Servers 
  ansible.windows.win_ping:

- name: Install java  on windows server
  chocolatey.chocolatey.win_chocolatey:
    name: temurin17
    state: present


- name: install postgresql on windows server
  chocolatey.chocolatey.win_chocolatey:
    name: postgresql
    state: present

- name: get the postgresql version details
  ansible.windows.win_shell: (Get-Service postgresql-x64-*).name
  register: postgresql_name
  changed_when: false

- name: Display Postgresql version
  debug:
    var: postgresql_name.stdout


- name: start postgresql server on windows server
  ansible.windows.win_service:
    name: "{{ postgresql_name.stdout | trim }}"
    state: started

- name: install chrome on windows 
  chocolatey.chocolatey.win_chocolatey:
    name: googlechrome
    state: present
    ignore_checksums: true

- name: Display current Working directory and files in it
  ansible.windows.command: ls

- name: copy zip files to Windows - server
  ansible.windows.win_copy:
    src: publish.zip
    dest: C:\publish.zip

