---
- name: ping windows Servers 
  ansible.windows.win_ping:

- name: Install java  on windows server
  chocolatey.chocolatey.win_chocolatey:
    name: temurin17
    state: present


- name: install postgresql on windows server
  chocolatey.chocolatey.win_chocolatey:
    name: postgresql
    state: present

- name: get the postgresql version details
  ansible.windows.win_shell: (Get-Service postgresql-x64-*).name
  register: postgresql_name
  changed_when: false

- name: Display Postgresql version
  debug:
    var: postgresql_name.stdout


- name: start postgresql server on windows server
  ansible.windows.win_service:
    name: "{{ postgresql_name.stdout | trim }}"
    state: started

- name: install chrome on windows 
  chocolatey.chocolatey.win_chocolatey:
    name: googlechrome
    state: present
    ignore_checksums: true


# ----------- Deployment ---


    # ---------------   Delete the previous files  -----------

- name: delete the temp file on the server  
  ansible.windows.win_file:
    path: C:\Temp
    state: absent

- name: delete zip file from the server 
  ansible.windows.win_file:
    path: C:\publish.zip
    state: absent

- name: Delete dll files
  ansible.windows.win_file:
    path: C:\webapp
    state: absent

- name: delete app win_iis_website
  ansible.windows.win_iis_website:
    name: WebApp 
    state: absent

- name: delete app pool
  ansible.windows.win_iis_webapppool:
    name: webapppool
    state: absent


# ------------  Adding the deleted files to deploy again  ----------

- name: Ensure C:\Temp exists
  ansible.windows.win_file:
    path: C:\Temp
    state: directory

- name: Download ASP.NET Core Hosting Bundle
  ansible.windows.win_get_url:
    url: https://builds.dotnet.microsoft.com/dotnet/aspnetcore/Runtime/9.0.17/dotnet-hosting-9.0.17-win.exe
    dest: C:\Temp\dotnet-hosting.exe

- name: Install ASP.NET Core Hosting Bundle
  ansible.windows.win_package:
    path: C:\Temp\dotnet-hosting.exe
    arguments: /install /repair /quiet /norestart
    state: present
    creates_path: C:\Program Files\IIS\Asp.Net Core Module\V2\

- name: Restart IIS to load the module
  ansible.windows.win_service:
    name: W3SVC
    state: restarted

- name: copy zip files to Windows - server
  ansible.windows.win_copy:
    src: publish.zip
    dest: C:\publish.zip

- name: Extract the zip files to the server
  community.windows.win_unzip:
    src: C:\publish.zip
    dest: C:\WebApp
    creates: C:\WebApp\publish\WebApp.dll

- name: Create IIS web app pool - no managed code
  community.windows.win_iis_webapppool:
    name: webapppool
    state: started
    attributes:
      managedRuntimeVersion: ""


- name: create iis wesite on port 8080
  community.windows.win_iis_website:
    name: WebApp
    state: started
    port: 8080
    physical_path: C:\WebApp\publish
    application_pool: webapppool

