---
- name: Test connectivity to Windows nodes
  hosts: windows
  gather_facts: false
  tasks:
    - name: Ping Windows hosts over WinRM
      ansible.windows.win_ping:


- name: test connectivity for linux nodes 
  hosts: linux
  gather_facts: true
  become: true
  tasks:
    - name: ping linux servers over ssh
      ansible.builtin.ping:

    - name: install postgresql
      ansible.builtin.dnf:
        name: postgresql
        state: present

    - name: Start postgresql service
      ansible.builtin.service:
        name: postgresql
        state: started
