---
- name: ping linux Servers
  ansible.builtin.ping:

- name: install java on linux
  ansible.builtin.dnf:
    name: java-17-amazon-corretto
    state: present

- name: install postgresql on linux
  ansible.builtin.dnf:
    name: postgresql15-server
    state: present

- name: setup postgresql server
  ansible.builtin.command: postgresql-setup --initdb
  args:
    creates: /var/lib/pgsql/data/PG_VERSION

- name: start postgresql on linux
  ansible.builtin.service:
    name: postgresql
    state: started
    enabled: true
  notify: 
    - Check_handlers
    - restart_postgresql

- name: install httpd on linux servers
  ansible.builtin.dnf:
    name: "{{web_package}}"
    state: present

- name: Start httpd service on linux servers
  ansible.builtin.service:
    name: "{{web_service}}"
    state: started
    enabled: true

# - name: Deploy index html on Linux Servers
#   ansible.builtin.copy:
#     src: "{{index_src}}"
#     dest: "{{index_dest}}"
#     owner: "{{deploy_owner}}"
#     mode: "{{file_mode}}"



# ---------   Deployment -----


- name: delete the files on the linux servers
  ansible.builtin.file:
    path: /opt/webapp
    state: absent
  become: true

- name: create a directory to copy application files
  ansible.builtin.file:
    path: /opt/webapp
    state: directory
  become: true

- name: extract zip files to the path  
  ansible.builtin.unarchive:
    src: publish.zip
    dest: /opt/webapp
    creates: /opt/webapp/publish/WebApp.dll
  become: true

