---

- name: install postgre sql
  dnf:
    name: postgresql15-Server
    state: present

- name: configure the postgre sql server
  command: postgresql-setup --initdb
  args:
    creates: /var/lib/pgsql/data/PG_VERSION

- name: Start postgresql server
  service:
    state: started
    enabled: true

