name: Configuration using Ansible

on: 
  push:
    branches:
      - ansible-16062026
  workflow_dispatch:

  
jobs:
  test:
    runs-on: ansible-1

    steps:
      - name: Test print 
        run: |
          echo "Hello world"

      - name: install Ansible
        run: |
          python3 -m pip install --user ansible pywinrm
          echo "$HOME/.local/bin" >> "$GITHUB_PATH"

      - name: Display Ansible version
        run: |
          ansible --version
          pywinrm --version

      - name: Checkout repo
        uses: actions/checkout@v4

      # - name: install Network Connectivity module
      #   run: sudo dnf install -y nmap-ncat

      - name: Check connectivity
        run: |
          curl -kv https://10.21.10.160:5986
          curl -kv https://10.21.10.93:5986
        
          # nc -zv 10.21.10.160 5986
          # nc -zv 10.21.10.93 5986


      - name: Display contents
        run: ls

        
        

          
    
