name: configure the Servers using Ansible - Playbook {{ github.run_number }}

on:
  push:
    branches:
      - ansible-16062026

  workflow_dispatch:

jobs:
  ansible-connectivity:
    runs-on: ansible-1

    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: Install ansible-1
        run: python3 -m pip install ansible

      - name: Display Ansible Version
        run: ansible --version

      - name: install boto3 
        run: pip install boto3

      - name: install aws collections from ansible-galaxy
        run: ansible-galaxy collection install amazon.aws

      # - name: call playbook
      #   env:
      #     WINDOWS_USER: ${{ secrets.WINDOWS_USER }}
      #     WINDOWS_PASSWORD: ${{ secrets.WINDOWS_PASSWORD }}
      #   run: |
      #     cd ansible
      #     ansible-playbook -i inventory/hosts.ini Playbooks/ping_servers.yml


      - name: check AWS connection
        run: ansible localhost -m amazon.aws.aws_caller_info

      - name: call ec2 playbook 
        run: |
          cd ansible
          ansible-playbook -i inventory/hosts.ini Playbooks/create_ec2.yml 



# name: Configuration using Ansible

# on: 
#   push:
#     branches:
#       - ansible-16062026
#   workflow_dispatch:

  
# jobs:
#   test:
#     runs-on: ansible-1

#     steps:
#       - name: Test print 
#         run: |
#           echo "Hello world"

#       - name: install Ansible
#         run: |
#           python3 -m pip install --user ansible pywinrm
#           echo "$HOME/.local/bin" >> "$GITHUB_PATH"

#       - name: Display Ansible version
#         run: |
#           ansible --version

#       - name: check the ssh id
#         run: which ssh-copy-id

#       - name: Checkout repo
#         uses: actions/checkout@v4

#       - name: Install Windows collection
#         run: ansible-galaxy collection install ansible.windows

#       - name: Run win_ping playbook
#         env:
#           WINDOWS_USER: ${{ secrets.WINDOWS_USER }}
#           WINDOWS_PASSWORD: ${{ secrets.WINDOWS_PASSWORD }}
#         run: |
#           cd ansible
#           ansible-playbook -i inventory/hosts.ini Playbooks/ping_servers.yml
