name: Configuration using Ansible

on: 
  push:
    branches:
      - ansible-16062026


  workflow_dispatch:



jobs:
  test:
    runs-on: ansible1

      steps:

        - name: Test print 
          run: |
            echo "Hello world"

          
    
