name: Test to install Packer

on:
  push:
    branches: 
      - Packer
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: winrunner1

    steps:
      - name: Install Packer
        shell: pwsh
        run: |
          choco install packer -y
          packer --version
